services:
postgres:
image: postgres:16
container_name: controle_financeiro_db_prod
restart: always

```
environment:
  POSTGRES_USER: henrique
  POSTGRES_PASSWORD: 123456
  POSTGRES_DB: controle_financeiro

ports:
  - "5432:5432"

volumes:
  - postgres_data_prod:/var/lib/postgresql/data

networks:
  - rede_prod
```

app:
build: .
container_name: controle_financeiro_app_prod
restart: always

```
ports:
  - "3000:3000"

env_file:
  - .env

depends_on:
  - postgres

networks:
  - rede_prod
```

volumes:
postgres_data_prod:

networks:
rede_prod:
