name: Deploy Homolog

on:

  push:
    branches:
      - homolog

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Deploy via SSH

        uses: appleboy/ssh-action@v1.2.0

        with:

          host: ${{ secrets.VM_HOST }}

          username: ${{ secrets.VM_USER }}

          key: ${{ secrets.VM_SSH_KEY }}

          script: |

            cd ~/Gerencia-de-configuracao

            git checkout homolog

            git pull origin homolog

            sudo docker compose \
            -f docker-compose.homolog.yml \
            -p homolog \
            up -d --build